# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "86154af1674159ac797f5767f244100c"
name = "Hebrew App"
handle = "hebrew-app-new"
application_url = "https://lose-bind-sword-soldier.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-store-emmy.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_themes,write_content,write_orders,write_products"

[auth]
redirect_urls = [
  "https://lose-bind-sword-soldier.trycloudflare.com/auth/callback",
  "https://lose-bind-sword-soldier.trycloudflare.com/auth/shopify/callback",
  "https://lose-bind-sword-soldier.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://lose-bind-sword-soldier.trycloudflare.com/proxy"
subpath = "order-cancellation"
prefix = "apps"
embedded = false
include_host = true

[pos]
embedded = false

[extensions.theme]
type = "theme_app_extension"
build_dir = ".shopify/bundle"

  [[extensions.theme.blocks]]
  name = "Order Cancellation Form"
  type = "order-cancellation-block"
  target = "section"
