# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "86154af1674159ac797f5767f244100c"
application_url = "https://becoming-announcement-mode-dependence.trycloudflare.com"
embedded = true
name = "TheHebrewAppReactNode"
handle = "thehebrewappreactnode"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-store-emmy.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_products"

[auth]
redirect_urls = [
  "https://becoming-announcement-mode-dependence.trycloudflare.com/auth/callback",
  "https://becoming-announcement-mode-dependence.trycloudflare.com/auth/shopify/callback",
  "https://becoming-announcement-mode-dependence.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
