# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "86154af1674159ac797f5767f244100c"
name = "Hebrew App"
handle = "hebrew-app-new"
application_url = "https://ci-sega-announce-pb.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-store-emmy.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_locales,read_markets_home,read_orders,read_products,read_themes,read_translations,write_content,write_locales,write_orders,write_products,write_translations"

[auth]
redirect_urls = ["https://ci-sega-announce-pb.trycloudflare.com/auth/callback", "https://ci-sega-announce-pb.trycloudflare.com/auth/shopify/callback", "https://ci-sega-announce-pb.trycloudflare.com/api/auth/callback"]

[app_proxy]
url = "https://ci-sega-announce-pb.trycloudflare.com/proxy"
subpath = "order-cancellation"
prefix = "apps"

[pos]
embedded = false
