name = "Hebrew App"
uid = "2ca6d3f1-dc71-3646-7a9e-98672f146d91c7a0fb62"
type = "theme"
icon = "assets/logo.svg"

[extension_points]
theme = "blocks/**/*"

[[block_types]]
type = "rtl_control" 
name = "RTL Control"
target = "body"

[[block_types]]
type = "cancellation_form"
name = "Transaction Cancellation Form" 
target = "section"
enabled_on = ["templates/page"]

[[assets]]
path = "assets/*"